# Generated by Django 5.1.4 on 2024-12-17 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0002_alter_pet_birth_date_alter_pet_breed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("activity", models.CharField(max_length=100)),
                ("date_completed", models.DateTimeField(auto_now_add=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pets.pet"
                    ),
                ),
            ],
        ),
    ]
