# Generated by Django 5.1.4 on 2025-02-18 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_name", models.CharField(default="", max_length=100)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("Walk", "Walk"),
                            ("Play", "Play"),
                            ("Feed", "Feed"),
                            ("Vet", "Vet"),
                            ("Groom", "Groom"),
                            ("Training", "Training"),
                            ("Medicine", "Medicine"),
                            ("Other", "Other"),
                        ],
                        default="Select Activity",
                        max_length=100,
                    ),
                ),
                ("activity", models.CharField(max_length=100)),
                ("date_completed", models.DateTimeField()),
                ("description", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="pets.pet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
