# Generated by Django 5.1.4 on 2024-12-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_activity_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="is_complete",
            new_name="is_completed",
        ),
        migrations.AddField(
            model_name="activity",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
