# Generated by Django 5.1.4 on 2025-01-06 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_activity_user"),
        ("pets", "0003_pet_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="pets.pet",
            ),
        ),
    ]
