# Generated by Django 5.1.4 on 2025-01-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0005_alter_activity_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="date_completed",
            field=models.DateTimeField(),
        ),
    ]
