# Generated by Django 5.1.4 on 2025-01-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0006_alter_activity_date_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="name",
        ),
        migrations.AddField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("Walk", "Walk"),
                    ("Play", "Play"),
                    ("Feed", "Feed"),
                    ("Vet", "Vet"),
                    ("Groom", "Groom"),
                    ("Training", "Training"),
                    ("Medicine", "Medicine"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=100,
            ),
        ),
    ]
