# Generated by Django 5.1.4 on 2025-01-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0007_remove_activity_name_activity_activity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="pet_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
