# Generated by Django 5.1.4 on 2025-01-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0008_activity_pet_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="pet_name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("Walk", "Walk"),
                    ("Play", "Play"),
                    ("Feed", "Feed"),
                    ("Vet", "Vet"),
                    ("Groom", "Groom"),
                    ("Training", "Training"),
                    ("Medicine", "Medicine"),
                    ("Other", "Other"),
                ],
                default="Select Activity",
                max_length=100,
            ),
        ),
    ]
