# Generated by Django 5.1.4 on 2025-01-25 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0009_rename_pet_name_activity_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="name",
            new_name="activity_name",
        ),
    ]
