# Generated by Django 5.1.4 on 2024-12-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pet",
            name="breed",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
