# Generated by Django 5.1.4 on 2024-12-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_alter_pet_birth_date_alter_pet_breed"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="photo",
            field=models.ImageField(blank=True, upload_to="pet_photos"),
        ),
    ]
