# Generated by Django 5.1.4 on 2025-01-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0003_pet_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="medical_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="vaccination_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
