# Generated by Django 5.1.4 on 2025-01-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petnote_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                default="stewartsamaira@gmail.com",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
