# Generated by Django 5.1.4 on 2025-02-15 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petnote_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="petnote_core_customuser",
        ),
    ]
