# Generated by Django 5.1.4 on 2025-02-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petnote_core", "0002_alter_customuser_options_alter_customuser_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images"),
        ),
    ]
