# Generated by Django 5.1.4 on 2025-01-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petnote_core", "0002_userprofile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
