# Generated by Django 5.1.4 on 2025-02-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petnote_core", "0003_customuser_bio_customuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
